- name: pip
  shell: pip install --upgrade pip
  ignore_errors: true

- pip: 
    name: jsbeautifier
  ignore_errors: true

- name: Run a script using an executable in a system path
  script: ./update_vars.py
  args:
    executable: python
  ignore_errors: true

